" A definição de compatibilidade não é necessária no Debian! ------------------
set nocompatible
" Definição das cores do terminal ---------------------------------------------
if has('termguicolors')
   set termguicolors
endif
" Configurações gerais --------------------------------------------------------
filetype plugin indent on
syntax on
set title
set encoding=utf-8
set backspace=indent,eol,start 
set noerrorbells
set confirm
set hidden
set splitbelow
set splitright
set mouse=a
" Caminhos --------------------------------------------------------------------
set path=.,**
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
" Variáveis -------------------------------------------------------------------
let $RCPATH = '~/.vim/'
let $RC = $RCPATH.'vimrc'
" Numeração de linhas ---------------------------------------------------------
set number 
set relativenumber
set scrolloff=2
set cursorline
" Mudança do cursor -----------------------------------------------------------
let &t_SI="\e[6 q"
let &t_EI="\e[2 q"
" Indentação ------------------------------------------------------------------
set autoindent
set smartindent
" Tabulações ------------------------------------------------------------------
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set colorcolumn=80
" Busca -----------------------------------------------------------------------
set ignorecase
set smartcase
set incsearch
set hls 
let @/ = ""
" Menu da barra de status -----------------------------------------------------
set wildmenu
set wildmode=longest,full
set wildoptions=pum
" Barra de status -------------------------------------------------------------
set noshowmode   " Negado para as definições da barra de status...
set laststatus=2
" Quebra de linha -------------------------------------------------------------
set nowrap 
set linebreak
" Caracteres de preenchimento -------------------------------------------------
set nolist 
set listchars=tab:›-,space:·,trail:◀,eol:↲
set fillchars=vert:│,fold:-,eob:~,lastline:@
" Ortografia ------------------------------------------------------------------
set nospell 
set spelllang=pt_br,en
" Menu do modo insert ---------------------------------------------------------
set complete+=kspell
set completeopt=menuone,longest
set shortmess+=c
" Esquema de cores ------------------------------------------------------------
colorscheme habamax
" Arquivos externos -----------------------------------------------------------
execute 'source '.$RCPATH.fnameescape('autocmds.vim')
execute 'source '.$RCPATH.fnameescape('customcolors.vim')
execute 'source '.$RCPATH.fnameescape('statusbar.vim')
execute 'source '.$RCPATH.fnameescape('mappings.vim')
" -----------------------------------------------------------------------------
execute 'source '.$RCPATH.fnameescape('icomplete.vim')
" -----------------------------------------------------------------------------

call plug#begin()
Plug 'instant-markdown/vim-instant-markdown', {'for': 'markdown', 'do': 'yarn install'}

call plug#end()

" Disable math tex conceal feature
let g:tex_conceal = ''
let g:vim_markdown_math = 1

" Markdown
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_frontmatter = 1
let g:vim_markdown_conceal = 0
let g:vim_markdown_fenced_languages = ['tsx=typescriptreact']
